name: CI
on:
  push:
    branches:
      - 'master'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: compiling
        run: mvn clean compile

      - name: Test
        run: mvn test

      - name: Test E2E
        run: mvn test -P E2E-tests