@startuml

title __TYPES's Class Diagram__\n

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace exceptions {
        namespace types {
          class ca.ulaval.glo4002.game.exceptions.types.DuplicateNameException {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace exceptions {
        namespace types {
          class ca.ulaval.glo4002.game.exceptions.types.InvalidFatherException {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace exceptions {
        namespace types {
          class ca.ulaval.glo4002.game.exceptions.types.InvalidGenderException {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace exceptions {
        namespace types {
          class ca.ulaval.glo4002.game.exceptions.types.InvalidMotherException {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace exceptions {
        namespace types {
          class ca.ulaval.glo4002.game.exceptions.types.InvalidResourceQuantityException {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace exceptions {
        namespace types {
          class ca.ulaval.glo4002.game.exceptions.types.InvalidSpeciesException {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace exceptions {
        namespace types {
          class ca.ulaval.glo4002.game.exceptions.types.InvalidWeightException {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace exceptions {
        namespace types {
          class ca.ulaval.glo4002.game.exceptions.types.NotExistentNameException {
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
