@startuml

title __CONFIGURATION's Class Diagram__\n

    namespace ca.ulaval.glo4002.game {
      namespace configuration {
        class ca.ulaval.glo4002.game.configuration.AppConfig {
            {static} + packageConfig : ResourceConfig
            {static} ~ actionFactory : ActionFactory
            {static} ~ actionRepository : ActionRepository
            {static} ~ dinosaurAssembler : DinosaurAssembler
            {static} ~ dinosaurDtoAssembler : DinosaurDtoAssembler
            {static} ~ dinosaurFactory : DinosaurFactory
            {static} ~ herdRepository : DinosaurRepository
            {static} ~ dinosaurResource : DinosaurResource
            {static} ~ dinosaurUseCase : DinosaurUseCase
            {static} ~ heartbeatResource : HeartbeatResource
            {static} ~ resourceAssembler : ResourceAssemblers
            {static} ~ resourceDtoAssembler : ResourceDtoAssembler
            {static} ~ resourceGroupFactory : ResourceFactory
            {static} ~ resourceRepository : ResourceRepository
            {static} ~ resourceResource : ResourceResource
            {static} ~ resourceUseCase : ResourceUseCase
            {static} ~ speciesDietsCorrespondances : SpeciesDietsCorrespondances
            {static} ~ turnAssembler : TurnAssembler
            {static} ~ turnDtoAssembler : TurnDtoAssembler
            {static} ~ turnFactory : TurnFactory
            {static} ~ turnRepository : TurnRepository
            {static} ~ turnResource : TurnResource
            {static} ~ turnUseCase : TurnUseCase
        }
      }
    }
  

    namespace ca.ulaval.glo4002.game {
      namespace configuration {
        class ca.ulaval.glo4002.game.configuration.CustomJsonProvider {
            {static} - mapper : ObjectMapper
            + CustomJsonProvider()
        }
      }
    }
  

  ca.ulaval.glo4002.game.configuration.CustomJsonProvider -up-|> org.glassfish.jersey.jackson.internal.jackson.jaxrs.json.JacksonJaxbJsonProvider


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
