@startuml

title __EXCEPTIONMAPPERS's Class Diagram__\n

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace exceptions {
        namespace exceptionMappers {
          class ca.ulaval.glo4002.game.exceptions.exceptionMappers.DuplicateNameExceptionsMapper {
              + toResponse()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace exceptions {
        namespace exceptionMappers {
          class ca.ulaval.glo4002.game.exceptions.exceptionMappers.InvalidFatherExceptionsMapper {
              + toResponse()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace exceptions {
        namespace exceptionMappers {
          class ca.ulaval.glo4002.game.exceptions.exceptionMappers.InvalidGenderExceptionsMapper {
              + toResponse()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace exceptions {
        namespace exceptionMappers {
          class ca.ulaval.glo4002.game.exceptions.exceptionMappers.InvalidMotherExceptionsMapper {
              + toResponse()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace exceptions {
        namespace exceptionMappers {
          class ca.ulaval.glo4002.game.exceptions.exceptionMappers.InvalidResourceExceptionsMapper {
              + toResponse()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace exceptions {
        namespace exceptionMappers {
          class ca.ulaval.glo4002.game.exceptions.exceptionMappers.InvalidSpeciesExceptionsMapper {
              + toResponse()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace exceptions {
        namespace exceptionMappers {
          class ca.ulaval.glo4002.game.exceptions.exceptionMappers.InvalidWeightExceptionsMapper {
              + toResponse()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace exceptions {
        namespace exceptionMappers {
          class ca.ulaval.glo4002.game.exceptions.exceptionMappers.NotExistentNameExceptionsMapper {
              + toResponse()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace exceptions {
        namespace exceptionMappers {
          class ca.ulaval.glo4002.game.exceptions.exceptionMappers.UnknownExceptionGrabber {
              + toResponse()
          }
        }
      }
    }
  }
  

  ca.ulaval.glo4002.game.exceptions.exceptionMappers.DuplicateNameExceptionsMapper .up.|> javax.ws.rs.ext.ExceptionMapper
  ca.ulaval.glo4002.game.exceptions.exceptionMappers.DuplicateNameExceptionsMapper -up-|> ca.ulaval.glo4002.game.exceptions.ExceptionsMapper
  ca.ulaval.glo4002.game.exceptions.exceptionMappers.InvalidFatherExceptionsMapper .up.|> javax.ws.rs.ext.ExceptionMapper
  ca.ulaval.glo4002.game.exceptions.exceptionMappers.InvalidFatherExceptionsMapper -up-|> ca.ulaval.glo4002.game.exceptions.ExceptionsMapper
  ca.ulaval.glo4002.game.exceptions.exceptionMappers.InvalidGenderExceptionsMapper .up.|> javax.ws.rs.ext.ExceptionMapper
  ca.ulaval.glo4002.game.exceptions.exceptionMappers.InvalidGenderExceptionsMapper -up-|> ca.ulaval.glo4002.game.exceptions.ExceptionsMapper
  ca.ulaval.glo4002.game.exceptions.exceptionMappers.InvalidMotherExceptionsMapper .up.|> javax.ws.rs.ext.ExceptionMapper
  ca.ulaval.glo4002.game.exceptions.exceptionMappers.InvalidMotherExceptionsMapper -up-|> ca.ulaval.glo4002.game.exceptions.ExceptionsMapper
  ca.ulaval.glo4002.game.exceptions.exceptionMappers.InvalidResourceExceptionsMapper .up.|> javax.ws.rs.ext.ExceptionMapper
  ca.ulaval.glo4002.game.exceptions.exceptionMappers.InvalidResourceExceptionsMapper -up-|> ca.ulaval.glo4002.game.exceptions.ExceptionsMapper
  ca.ulaval.glo4002.game.exceptions.exceptionMappers.InvalidSpeciesExceptionsMapper .up.|> javax.ws.rs.ext.ExceptionMapper
  ca.ulaval.glo4002.game.exceptions.exceptionMappers.InvalidSpeciesExceptionsMapper -up-|> ca.ulaval.glo4002.game.exceptions.ExceptionsMapper
  ca.ulaval.glo4002.game.exceptions.exceptionMappers.InvalidWeightExceptionsMapper .up.|> javax.ws.rs.ext.ExceptionMapper
  ca.ulaval.glo4002.game.exceptions.exceptionMappers.InvalidWeightExceptionsMapper -up-|> ca.ulaval.glo4002.game.exceptions.ExceptionsMapper
  ca.ulaval.glo4002.game.exceptions.exceptionMappers.NotExistentNameExceptionsMapper .up.|> javax.ws.rs.ext.ExceptionMapper
  ca.ulaval.glo4002.game.exceptions.exceptionMappers.NotExistentNameExceptionsMapper -up-|> ca.ulaval.glo4002.game.exceptions.ExceptionsMapper
  ca.ulaval.glo4002.game.exceptions.exceptionMappers.UnknownExceptionGrabber .up.|> javax.ws.rs.ext.ExceptionMapper


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
