@startuml

title __RESOURCES's Class Diagram__\n

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace domain.resourceGroup {
        class ca.ulaval.glo4002.game.domain.resourceGroup.Burger {
            - expiration : int
            + Burger()
            + decreaseExpirationDate()
            + getDaysLeft()
        }
      }
    }
  }
  

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace domain.resourceGroup {
        class ca.ulaval.glo4002.game.domain.resources.ResourceGrouprces {
            - resourceGroup : Map<String, ResourceElements>
            + Resource()
            + addBurger()
            + addSalad()
            + addWater()
            + clear()
            + getBurgersQuantity()
            + getResources()
            + getSaladQuantity()
            + getWaterQuantity()
        }
      }
    }
  }
  

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace domain.resourceGroup {
        abstract class ca.ulaval.glo4002.game.domain.resourceGroup.Resource {
            - quantity : int
            + ResourceElements()
            + addQuantity()
            {abstract} + decreaseExpirationDate()
            {abstract} + getDaysLeft()
            + getQuantity()
            + removeElement()
            + reset()
            + setQuantity()
        }
      }
    }
  }
  

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace domain.resourceGroup {
        class ca.ulaval.glo4002.game.domain.resourceGroup.ResourcesFactory {
            + create()
        }
      }
    }
  }
  

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace domain.resourceGroup {
        interface ca.ulaval.glo4002.game.domain.resourceGroup.ResourceRepository {
            {abstract} + add()
            {abstract} + decreaseExpirationDate()
            {abstract} + drinkWater()
            {abstract} + eatBurger()
            {abstract} + eatSalad()
            {abstract} + findAll()
            {abstract} + findConsumedResource()
            {abstract} + findExpiredResource()
            {abstract} + findFreshResource()
            {abstract} + findResourceQuantity()
            {abstract} + reset()
        }
      }
    }
  }
  

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace domain.resourceGroup {
        class ca.ulaval.glo4002.game.domain.resourceGroup.Salad {
            - expiration : int
            + Salad()
            + decreaseExpirationDate()
            + getDaysLeft()
        }
      }
    }
  }
  

  namespace  {
    namespace a.ulaval.glo4002.game {
      namespace domain.resourceGroup {
        class ca.ulaval.glo4002.game.domain.resourceGroup.Water {
            - expiration : int
            + Water()
            + decreaseExpirationDate()
            + getDaysLeft()
        }
      }
    }
  }
  

  ca.ulaval.glo4002.game.domain.resourceGroup.Burger -up-|> ca.ulaval.glo4002.game.domain.resourceGroup.Resource
  ca.ulaval.glo4002.game.domain.resourceGroup.Salad -up-|> ca.ulaval.glo4002.game.domain.resourceGroup.Resource
  ca.ulaval.glo4002.game.domain.resourceGroup.Water -up-|> ca.ulaval.glo4002.game.domain.resourceGroup.Resource


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
