@startuml

title __ENTITIES's Class Diagram__\n

  namespace ca.ulaval.glo4002.game {
    namespace interfaces.rest {
      namespace exceptions {
        namespace entities {
          class ca.ulaval.glo4002.game.interfaces.rest.exceptions.entities.DuplicateNameException {
          }
        }
      }
    }
  }
  

  namespace ca.ulaval.glo4002.game {
    namespace interfaces.rest {
      namespace exceptions {
        namespace entities {
          class ca.ulaval.glo4002.game.interfaces.rest.exceptions.entities.InvalidGenderException {
          }
        }
      }
    }
  }
  

  namespace ca.ulaval.glo4002.game {
    namespace interfaces.rest {
      namespace exceptions {
        namespace entities {
          class ca.ulaval.glo4002.game.interfaces.rest.exceptions.entities.InvalidResourceQuantityException {
          }
        }
      }
    }
  }
  

  namespace ca.ulaval.glo4002.game {
    namespace interfaces.rest {
      namespace exceptions {
        namespace entities {
          class ca.ulaval.glo4002.game.interfaces.rest.exceptions.entities.InvalidSpeciesException {
          }
        }
      }
    }
  }
  

  namespace ca.ulaval.glo4002.game {
    namespace interfaces.rest {
      namespace exceptions {
        namespace entities {
          class ca.ulaval.glo4002.game.interfaces.rest.exceptions.entities.InvalidWeightException {
          }
        }
      }
    }
  }
  

  namespace ca.ulaval.glo4002.game {
    namespace interfaces.rest {
      namespace exceptions {
        namespace entities {
          class ca.ulaval.glo4002.game.interfaces.rest.exceptions.entities.NotExistentNameException {
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
