@startuml

title __DTOS's Class Diagram__\n

    namespace ca.ulaval.glo4002.game {
      namespace controllers.dinosaur {
        namespace dtos {
          class ca.ulaval.glo4002.game.application.dinosaur.dtos.DinosaurAssembler {
              + toDto()
              + toDtos()
          }
        }
      }
    }
  

    namespace ca.ulaval.glo4002.game {
      namespace controllers.dinosaur {
        namespace dtos {
          class ca.ulaval.glo4002.game.controllers.dinosaur.dtos.DinosaurCreationDto {
              + gender : String
              + name : String
              + species : String
              + weight : int
          }
        }
      }
    }
  

    namespace ca.ulaval.glo4002.game {
      namespace controllers.dinosaur {
        namespace dtos {
          class ca.ulaval.glo4002.game.application.dinosaur.dtos.DinosaurDto {
              + gender : String
              + name : String
              + species : String
              + weight : int
          }
        }
      }
    }
  

    namespace ca.ulaval.glo4002.game {
      namespace controllers.dinosaur {
        namespace dtos {
          class ca.ulaval.glo4002.game.controllers.dinosaur.dtos.DinosaurDtoAssembler {
              + fromRequest()
              + toResponse()
              + toResponse()
          }
        }
      }
    }
  

    namespace ca.ulaval.glo4002.game {
      namespace controllers.dinosaur {
        namespace dtos {
          class ca.ulaval.glo4002.game.controllers.dinosaur.dtos.DinosaurRequest {
              + gender : String
              + name : String
              + species : String
              + weight : int
          }
        }
      }
    }

    namespace ca.ulaval.glo4002.game {
      namespace controllers.dinosaur {
        namespace dtos {
          class ca.ulaval.glo4002.game.controllers.dinosaur.dtos.DinosaurResponseItem {
              + gender : String
              + name : String
              + species : String
              + weight : int
          }
        }
      }
    }
  

    namespace ca.ulaval.glo4002.game {
      namespace controllers.dinosaur {
        namespace dtos {
          class ca.ulaval.glo4002.game.controllers.dinosaur.dtos.DinosaursResponse {
              + items : List<DinosaurResponseItem>
          }
        }
      }
    }
  

  ca.ulaval.glo4002.game.controllers.dinosaur.dtos.DinosaurDtoAssembler o-- ca.ulaval.glo4002.game.application.dinosaur.DinosaurFactory : dinosaurFactory


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
